// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3xwBR1S-95CIfa0D1PutibHfrWjAggC4',
    appId: '1:45679077994:web:c868411301f4a1f126b813',
    messagingSenderId: '45679077994',
    projectId: 'nbc-app-5b29a',
    authDomain: 'nbc-app-5b29a.firebaseapp.com',
    storageBucket: 'nbc-app-5b29a.appspot.com',
    measurementId: 'G-JEF9HZ41TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_NsbE-w7ANlRHU_j8Zb6Ml8nt8Kl6jjU',
    appId: '1:45679077994:android:70b00201e69ed1bd26b813',
    messagingSenderId: '45679077994',
    projectId: 'nbc-app-5b29a',
    storageBucket: 'nbc-app-5b29a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC4A5kr2ZUmlYxpTn7wonUn2aFWpTkO1o',
    appId: '1:45679077994:ios:46972a1a5f2c789326b813',
    messagingSenderId: '45679077994',
    projectId: 'nbc-app-5b29a',
    storageBucket: 'nbc-app-5b29a.appspot.com',
    iosBundleId: 'com.example.nbcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC4A5kr2ZUmlYxpTn7wonUn2aFWpTkO1o',
    appId: '1:45679077994:ios:e119e5a64c3bcdd726b813',
    messagingSenderId: '45679077994',
    projectId: 'nbc-app-5b29a',
    storageBucket: 'nbc-app-5b29a.appspot.com',
    iosBundleId: 'com.example.nbcApp.RunnerTests',
  );
}
